# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Go.gitlab-ci.yml

image: golang:latest

stages:
  - test
  - build
  - deploy

before_script:
  - go version  # Print out python version for debugging

  # 更新PyPi
  - apt update

  # 安裝虛擬環境
  - apt install git make wget build-essential -y -f
  - apt install tzdata ca-certificates -y -f

format:
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

compile:
  stage: build
  script:
    - mkdir -p mybinaries
    - go build -o mybinaries ./...
  artifacts:
    paths:
      - mybinaries

deploy:
  stage: deploy
  script:
    - make
    - wget https://github.com/v2fly/domain-list-community/raw/release/dlc.dat -O build/geosite.dat
    - wget https://github.com/Loyalsoldier/geoip/raw/release/geoip.dat -O build/geoip.dat
    - wget https://github.com/Loyalsoldier/geoip/raw/release/geoip-only-cn-private.dat -O build/geoip-only-cn-private.dat
    - mv build trojan-go
    - mv example/server.json trojan-go/config.json
  environment: production
  artifacts:
    paths:
      - dist/*.whl
