// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: api.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrojanClientService_GetTraffic_FullMethodName = "/trojan.api.TrojanClientService/GetTraffic"
)

// TrojanClientServiceClient is the client API for TrojanClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrojanClientServiceClient interface {
	GetTraffic(ctx context.Context, in *GetTrafficRequest, opts ...grpc.CallOption) (*GetTrafficResponse, error)
}

type trojanClientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrojanClientServiceClient(cc grpc.ClientConnInterface) TrojanClientServiceClient {
	return &trojanClientServiceClient{cc}
}

func (c *trojanClientServiceClient) GetTraffic(ctx context.Context, in *GetTrafficRequest, opts ...grpc.CallOption) (*GetTrafficResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrafficResponse)
	err := c.cc.Invoke(ctx, TrojanClientService_GetTraffic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrojanClientServiceServer is the server API for TrojanClientService service.
// All implementations must embed UnimplementedTrojanClientServiceServer
// for forward compatibility.
type TrojanClientServiceServer interface {
	GetTraffic(context.Context, *GetTrafficRequest) (*GetTrafficResponse, error)
	mustEmbedUnimplementedTrojanClientServiceServer()
}

// UnimplementedTrojanClientServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrojanClientServiceServer struct{}

func (UnimplementedTrojanClientServiceServer) GetTraffic(context.Context, *GetTrafficRequest) (*GetTrafficResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTraffic not implemented")
}
func (UnimplementedTrojanClientServiceServer) mustEmbedUnimplementedTrojanClientServiceServer() {}
func (UnimplementedTrojanClientServiceServer) testEmbeddedByValue()                             {}

// UnsafeTrojanClientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrojanClientServiceServer will
// result in compilation errors.
type UnsafeTrojanClientServiceServer interface {
	mustEmbedUnimplementedTrojanClientServiceServer()
}

func RegisterTrojanClientServiceServer(s grpc.ServiceRegistrar, srv TrojanClientServiceServer) {
	// If the following call panics, it indicates UnimplementedTrojanClientServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrojanClientService_ServiceDesc, srv)
}

func _TrojanClientService_GetTraffic_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(GetTrafficRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrojanClientServiceServer).GetTraffic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrojanClientService_GetTraffic_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(TrojanClientServiceServer).GetTraffic(ctx, req.(*GetTrafficRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrojanClientService_ServiceDesc is the grpc.ServiceDesc for TrojanClientService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrojanClientService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trojan.api.TrojanClientService",
	HandlerType: (*TrojanClientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTraffic",
			Handler:    _TrojanClientService_GetTraffic_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

const (
	TrojanServerService_ListUsers_FullMethodName         = "/trojan.api.TrojanServerService/ListUsers"
	TrojanServerService_GetUsers_FullMethodName          = "/trojan.api.TrojanServerService/GetUsers"
	TrojanServerService_SetUsers_FullMethodName          = "/trojan.api.TrojanServerService/SetUsers"
	TrojanServerService_GetRecords_FullMethodName        = "/trojan.api.TrojanServerService/GetRecords"
	TrojanServerService_SetOutboundConfig_FullMethodName = "/trojan.api.TrojanServerService/SetOutboundConfig"
	TrojanServerService_GetOutboundConfig_FullMethodName = "/trojan.api.TrojanServerService/GetOutboundConfig"
)

// TrojanServerServiceClient is the client API for TrojanServerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrojanServerServiceClient interface {
	// list all users
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListUsersResponse], error)
	// obtain specified user's info
	GetUsers(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GetUsersRequest, GetUsersResponse], error)
	// setup existing users' config
	SetUsers(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SetUsersRequest, SetUsersResponse], error)
	// get traffic records
	GetRecords(ctx context.Context, in *GetRecordsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetRecordsResponse], error)
	// set freedom outbound local addr / fwmark at runtime
	SetOutboundConfig(ctx context.Context, in *SetOutboundConfigRequest, opts ...grpc.CallOption) (*SetOutboundConfigResponse, error)
	// get current freedom outbound local addr / fwmark
	GetOutboundConfig(ctx context.Context, in *GetOutboundConfigRequest, opts ...grpc.CallOption) (*GetOutboundConfigResponse, error)
}

type trojanServerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrojanServerServiceClient(cc grpc.ClientConnInterface) TrojanServerServiceClient {
	return &trojanServerServiceClient{cc}
}

func (c *trojanServerServiceClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListUsersResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TrojanServerService_ServiceDesc.Streams[0], TrojanServerService_ListUsers_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListUsersRequest, ListUsersResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrojanServerService_ListUsersClient = grpc.ServerStreamingClient[ListUsersResponse]

func (c *trojanServerServiceClient) GetUsers(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GetUsersRequest, GetUsersResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TrojanServerService_ServiceDesc.Streams[1], TrojanServerService_GetUsers_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetUsersRequest, GetUsersResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrojanServerService_GetUsersClient = grpc.BidiStreamingClient[GetUsersRequest, GetUsersResponse]

func (c *trojanServerServiceClient) SetUsers(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SetUsersRequest, SetUsersResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TrojanServerService_ServiceDesc.Streams[2], TrojanServerService_SetUsers_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SetUsersRequest, SetUsersResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrojanServerService_SetUsersClient = grpc.BidiStreamingClient[SetUsersRequest, SetUsersResponse]

func (c *trojanServerServiceClient) GetRecords(ctx context.Context, in *GetRecordsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetRecordsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TrojanServerService_ServiceDesc.Streams[3], TrojanServerService_GetRecords_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetRecordsRequest, GetRecordsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrojanServerService_GetRecordsClient = grpc.ServerStreamingClient[GetRecordsResponse]

func (c *trojanServerServiceClient) SetOutboundConfig(ctx context.Context, in *SetOutboundConfigRequest, opts ...grpc.CallOption) (*SetOutboundConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetOutboundConfigResponse)
	err := c.cc.Invoke(ctx, TrojanServerService_SetOutboundConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trojanServerServiceClient) GetOutboundConfig(ctx context.Context, in *GetOutboundConfigRequest, opts ...grpc.CallOption) (*GetOutboundConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOutboundConfigResponse)
	err := c.cc.Invoke(ctx, TrojanServerService_GetOutboundConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrojanServerServiceServer is the server API for TrojanServerService service.
// All implementations must embed UnimplementedTrojanServerServiceServer
// for forward compatibility.
type TrojanServerServiceServer interface {
	// list all users
	ListUsers(*ListUsersRequest, grpc.ServerStreamingServer[ListUsersResponse]) error
	// obtain specified user's info
	GetUsers(grpc.BidiStreamingServer[GetUsersRequest, GetUsersResponse]) error
	// setup existing users' config
	SetUsers(grpc.BidiStreamingServer[SetUsersRequest, SetUsersResponse]) error
	// get traffic records
	GetRecords(*GetRecordsRequest, grpc.ServerStreamingServer[GetRecordsResponse]) error
	// set freedom outbound local addr / fwmark at runtime
	SetOutboundConfig(context.Context, *SetOutboundConfigRequest) (*SetOutboundConfigResponse, error)
	// get current freedom outbound local addr / fwmark
	GetOutboundConfig(context.Context, *GetOutboundConfigRequest) (*GetOutboundConfigResponse, error)
	mustEmbedUnimplementedTrojanServerServiceServer()
}

// UnimplementedTrojanServerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrojanServerServiceServer struct{}

func (UnimplementedTrojanServerServiceServer) ListUsers(*ListUsersRequest, grpc.ServerStreamingServer[ListUsersResponse]) error {
	return status.Error(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedTrojanServerServiceServer) GetUsers(grpc.BidiStreamingServer[GetUsersRequest, GetUsersResponse]) error {
	return status.Error(codes.Unimplemented, "method GetUsers not implemented")
}
func (UnimplementedTrojanServerServiceServer) SetUsers(grpc.BidiStreamingServer[SetUsersRequest, SetUsersResponse]) error {
	return status.Error(codes.Unimplemented, "method SetUsers not implemented")
}
func (UnimplementedTrojanServerServiceServer) GetRecords(*GetRecordsRequest, grpc.ServerStreamingServer[GetRecordsResponse]) error {
	return status.Error(codes.Unimplemented, "method GetRecords not implemented")
}
func (UnimplementedTrojanServerServiceServer) SetOutboundConfig(context.Context, *SetOutboundConfigRequest) (*SetOutboundConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetOutboundConfig not implemented")
}
func (UnimplementedTrojanServerServiceServer) GetOutboundConfig(context.Context, *GetOutboundConfigRequest) (*GetOutboundConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOutboundConfig not implemented")
}
func (UnimplementedTrojanServerServiceServer) mustEmbedUnimplementedTrojanServerServiceServer() {}
func (UnimplementedTrojanServerServiceServer) testEmbeddedByValue()                             {}

// UnsafeTrojanServerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrojanServerServiceServer will
// result in compilation errors.
type UnsafeTrojanServerServiceServer interface {
	mustEmbedUnimplementedTrojanServerServiceServer()
}

func RegisterTrojanServerServiceServer(s grpc.ServiceRegistrar, srv TrojanServerServiceServer) {
	// If the following call panics, it indicates UnimplementedTrojanServerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrojanServerService_ServiceDesc, srv)
}

func _TrojanServerService_ListUsers_Handler(srv any, stream grpc.ServerStream) error {
	m := new(ListUsersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TrojanServerServiceServer).ListUsers(m, &grpc.GenericServerStream[ListUsersRequest, ListUsersResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrojanServerService_ListUsersServer = grpc.ServerStreamingServer[ListUsersResponse]

func _TrojanServerService_GetUsers_Handler(srv any, stream grpc.ServerStream) error {
	return srv.(TrojanServerServiceServer).GetUsers(&grpc.GenericServerStream[GetUsersRequest, GetUsersResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrojanServerService_GetUsersServer = grpc.BidiStreamingServer[GetUsersRequest, GetUsersResponse]

func _TrojanServerService_SetUsers_Handler(srv any, stream grpc.ServerStream) error {
	return srv.(TrojanServerServiceServer).SetUsers(&grpc.GenericServerStream[SetUsersRequest, SetUsersResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrojanServerService_SetUsersServer = grpc.BidiStreamingServer[SetUsersRequest, SetUsersResponse]

func _TrojanServerService_GetRecords_Handler(srv any, stream grpc.ServerStream) error {
	m := new(GetRecordsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TrojanServerServiceServer).GetRecords(m, &grpc.GenericServerStream[GetRecordsRequest, GetRecordsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrojanServerService_GetRecordsServer = grpc.ServerStreamingServer[GetRecordsResponse]

func _TrojanServerService_SetOutboundConfig_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(SetOutboundConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrojanServerServiceServer).SetOutboundConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrojanServerService_SetOutboundConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(TrojanServerServiceServer).SetOutboundConfig(ctx, req.(*SetOutboundConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrojanServerService_GetOutboundConfig_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(GetOutboundConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrojanServerServiceServer).GetOutboundConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrojanServerService_GetOutboundConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(TrojanServerServiceServer).GetOutboundConfig(ctx, req.(*GetOutboundConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrojanServerService_ServiceDesc is the grpc.ServiceDesc for TrojanServerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrojanServerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trojan.api.TrojanServerService",
	HandlerType: (*TrojanServerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetOutboundConfig",
			Handler:    _TrojanServerService_SetOutboundConfig_Handler,
		},
		{
			MethodName: "GetOutboundConfig",
			Handler:    _TrojanServerService_GetOutboundConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListUsers",
			Handler:       _TrojanServerService_ListUsers_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetUsers",
			Handler:       _TrojanServerService_GetUsers_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SetUsers",
			Handler:       _TrojanServerService_SetUsers_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "GetRecords",
			Handler:       _TrojanServerService_GetRecords_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api.proto",
}
