name: docker-release
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'docs/**'
    tags: # let the GitHub CI with new tag release trigger this docker build GitHub CI
      - '**' # Push events to every tag including hierarchical tags like v1.0/beta
    
jobs:
  build:
    if: github.repository == 'Potterli20/trojan-go'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@main

      - name: Setup QEMU
        uses: docker/setup-qemu-action@master

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Login to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWORD }}

      - name: Prepare
        id: prepare
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo ::set-output name=ref::${GITHUB_REF#refs/tags/}
          else
            echo ::set-output name=ref::${{ github.sha }}
          fi
          echo ::set-output name=docker_platforms::linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386
          echo ::set-output name=docker_image::${{ secrets.DOCKERUSERNAME }}/trojan-go
      - name: Build and push docker image
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            docker buildx build --platform ${{ steps.prepare.outputs.docker_platforms }} \
            --output "type=image,push=true" \
            --tag "${{ steps.prepare.outputs.docker_image }}:${GITHUB_REF#refs/tags/}" \
            --tag "${{ steps.prepare.outputs.docker_image }}:latest" \
            --build-arg REF=${{ steps.prepare.outputs.ref }} \
            --file Dockerfile .
          else
            docker buildx build --platform ${{ steps.prepare.outputs.docker_platforms }} \
            --output "type=image,push=true" \
            --tag "${{ steps.prepare.outputs.docker_image }}:snapshot" \
            --build-arg REF=${{ steps.prepare.outputs.ref }} \
            --file Dockerfile .
          fi
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test docker image
        run: |
          docker run --rm --entrypoint /usr/local/bin/trojan-go ${{ secrets.DOCKERUSERNAME }}/trojan-go -version
